version: '3.9'

services:
  back:
    build: back/
    container_name: backend
    env_file: ./.env
    depends_on:
      - db
    ports:
      - 3001:3001
    environment:
      - DB_HOST=db_app
    command: yarn dev

  db:
    image: postgres:14.2
    container_name: db_app
    env_file: ./.env
    restart: always
    ports: 
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
    volumes:
      - pg_data:/var/lib/postgresql/data
    tty: true

  migration:
    build:
      context: ./back
    container_name: db_migration_check
    env_file: ./.env
    command:
      [
        "./wait-for-it/wait-for-it.sh",
        "db:5432",
        "--",
        "yarn",
        "sequelize",
        "db:migrate"
      ]
    links:
      - db
    depends_on:
      - db
    environment:
      - DB_HOST=db_app

volumes:
  pg_data: null