version: '3.8'

services:
  db:
    image: postgres:14.2
    container_name: pizzaria
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_DB=pizzaria
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
