version: '3.9'

services:
  db:
    image: postgres:14.2
    container_name: pizzaria
    env_file: ./.env
    restart: always
    ports: 
      - 5432:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
